blank_issues_enabled: false
contact_links:
  - name: ⬇ Installation Help
    url: https://discord.gg/YwmWmEumvw
    about: Please join my Discord if you are experiencing issues with installation
  - name: ❓ General Question
    url: https://discord.gg/YwmWmEumvw
    about: Please join my Discord if you have any questions!